spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dbname?useSSL=false&characterEncoding=utf-8
    username: root
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    druid:
      initial-size: 5
      filters: stat,slf4j
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-connect-error-millis: 60000
      test-on-return: false
      test-on-borrow: false
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      filter:
          stat:
            log-slow-sql: true




